//
//  QuizInteractor.swift
//  Code Quiz
//
//  Created by Felipe on 02/09/19.
//  Copyright (c) 2019 Felipe de Lara. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class QuizInteractor {
}

// MARK: - Extensions -

extension QuizInteractor: QuizInteractorInterface {
    func fetchCorrectKeywords(onCompletion : @escaping (Bool, Keywords?)->Void){
        KeywordsService.request(completionHandler: onCompletion)
    }
}
