//
//  QuizInterfaces.swift
//  Code Quiz
//
//  Created by Felipe on 02/09/19.
//  Copyright (c) 2019 Felipe de Lara. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol QuizWireframeInterface: WireframeInterface {
    //Presenter to Router
    //func presentScoreList()
    //func presentCorrectAnswers
}

protocol QuizViewInterface: ViewInterface {
    //Presenter to View
    func showLoading()
    func hideLoading()
    func showVictory()
    func presentAlert(title: String, message: String, actionTitle: String, actionClosure: @escaping (() -> Void))
    func updateGame(toFitState state: GameState)
    func setTitle(text: String)
    func setTable(tableData: [String])
    func setCounter(time: String)
    func setScore(score: String)
    func clearTextField()
    func setupInitialView()
}

protocol QuizPresenterInterface: PresenterInterface {
    // View to presenter
    func notifyViewDidLoad()
    func notifyViewDidAppear()
    func keyworkdsTextViewDidChange(text: String)
    func mainButtonPressed()
    
    // Interactor to presenter
    func keywordsFetchSuccess(keywords: Keywords)
    func keywordsFetchFailed(with errorMessage: String)
}

protocol QuizInteractorInterface: InteractorInterface {
    //Presenter to Interactor
    func fetchCorrectKeywords(onCompletion : @escaping (Bool, Keywords?)->Void)
}
